- hosts: go-api-service
  become: true
  tasks:
    - name: Provide the configuration files for the webserver.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: go
        group: sudo
        mode: "u=rw,g=r,o=r"
      with_items:
        - {src: "files/uwsgi_api.ini", dest: "{{ go.home }}/conf/uwsgi_api.ini"}
        - {src: "files/nginx_api.conf", dest: "{{ go.home }}/conf/nginx_api.conf"}

    - name: Create the necessary log file and directory.
      file:
        path: "{{ item.dest }}"
        owner: go
        group: sudo
        mode: "{{ item.mode }}"
        state: "{{ item.state }}"
      with_items:
        - { dest: "{{ go.logs_dir }}", mode: "u=rwx,g=rx,o=rx", state: directory }
        - { dest: "{{ go.logs_dir }}/api_uwsgi.log", mode: "u=rw,g=r,o=r", state: touch }
        - { dest: "{{ go.logs_api }}", mode: "u=rw,g=r,o=r", state: touch }

    - name: Provide the necessary go-service package.
      copy:
        src: "./go_service"
        dest: "{{ go.home }}"
        owner: go
        group: sudo
        mode: "u=rw,g=r,o=r"

    - name: Start the GO API
      docker_container:
        name: go-api
        image: "go-service:latest"
        working_dir: "/app/go_service"
        hostname: go-service-api
        recreate: yes
        env:
          UWSGI_INI: "/app/go_service/uwsgi.ini"
        networks:
          - name: "{{ go_network.name }}"
        published_ports:
          - 12001:12001
        volumes:
          - "{{ go.logs_api }}:/app/logs/go-service-api.log"
          - "{{ go.home }}/go_service:/app/go_service"
          - "{{ go.home }}/conf/uwsgi_api.ini:/app/go_service/uwsgi.ini"
          - "{{ go.logs_dir }}/api_uwsgi.log:/app/logs/api_uwsgi.log"
          - "{{ go.home }}/conf/nginx_api.conf:/etc/nginx/conf.d/nginx_api.conf"
        restart_policy: always
        state: started
        restart: yes
