FROM tiangolo/uwsgi-nginx-flask:python3.6

ENV https_proxy {{ company_proxy }}
ENV http_proxy {{ company_proxy }}
ENV HTTPS_PROXY {{ company_proxy }}
ENV HTTP_PROXY {{ company_proxy }}

RUN apt-get update && apt-get install -y ldap-utils build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install flask-jwt-extended ldap3 eve pymongo flask-cors
RUN adduser --system --disabled-password --home {{ go.home }} --uid {{ go.uid }} --ingroup root go
