name: CI

on: [push, pull_request]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
        working-directory: frontend
      - name: Run ESLint
        run: yarn run eslint . --ext .js,.jsx
        working-directory: frontend
